# What is Bioinformatics?

Bioinformatics, as it pertains to this book, is the use of computational tools to process biological data. As science has progressed, the datasets produced during scientific experiments have become larger and larger and therefore the ability to glean insights from the data has become less and less straightforward. The growing complexity and size of scientific data has necessitated an increased reliance on computational tools for storing, analyzing, and visualizing data. The past 20 years of scientific research since the complete sequencing of the human genome has seen vast increases in the types of data generated and the number of tools used to process it. Several tools that will be discussed throughout this book have emerged as vital resources for processing particular types of biological data. This book will explore what types of biological data are out there, what tools are available to process it, and how you can begin processing data on your own computer.

## Common terms to understand

In this book, and throughout your time engaged with bioinformatics, you will encounter many terms that may not be in your everyday lexicon but will become invaluable to successful computing. While some terms may describe new ideas to you, others may be synonyms for terms you are more familiar with but are necessary to use when dealing with computers. Though not an exhaustive list, below are several of the terms you may encounter in bioinformatics:

| **code:** a group of text, when executed, that performs a computational task

| **directory:** a place where files are stored; synonymous with "folder"

| **execute:**
| (a) to run a line of code or script
| (b) in reference to privileges, the ability to run a script

| **read:**
| (a) a single sequence letters corresponding to nucleotide bases of DNA or RNA
| (b) in references to privileges, the ability to open and view a file or directory

| **script:** a file that contains multiple lines of code that collectively perform a computational task

| **write:** in references to privileges, to add to a file or directory
